- name: Install Docker and Docker Compose
  hosts: servers
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      become: true

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        validate_certs: no
      become: true
    - name: Change ownership and permissions of docker-compose
      file:
        path: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 'u+x,g+x,o+x'
      become: true

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Pull Docker image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull

    - name: Install pip package manager
      become: true
      package:
        name: python3-pip
        state: present
    - name: Install docker Python library
      pip:
        name: docker
        state: present
        executable: pip3
    - name: Run Docker Compose
      docker_compose:
        project_src: "{{ ansible_env.docker_compose_path }}"
        state: present
        build: no
        pull: yes
      environment:
        DOCKER_IMAGE: "{{ DOCKER_IMAGE }}"
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
