version: '3'
services:
  javaapp:
    image: ${DOCKER_IMAGE}
    ports:
      - 8080:8080
    environment:
      - DB_HOST=your_database_host
      - DB_PORT=your_database_port
      - DB_NAME=your_database_name
      - DB_USERNAME=your_database_username
      - DB_PASSWORD=your_database_password
